### ISSUE TITLE
I can't get four 32x8 panels to work.

### ISSUE THREAD

**Issue by TWICExONCE** [lyriarte/StripDisplay#3]
I am using the Arduino Mega. There's enough space for the program. When I run it with 3 panels it works but when I add the 4th it stops working, Here's the code I modified.

#define FONT_5x7_FIXED_MEDIUM
#include <StripDisplay.h>
XBMFont * fontP = &fixedMedium_5x7;

#define STRIPLED_GPIO 5
#define BITMAP_W	64
#define BITMAP_H	16
#define STRIPLED_W	32
#define STRIPLED_H	8

// stack four 32x8 panels 1st top left, 2nd top right, 3rd bottom left, 4th bottom right to create 64x16
StripLEDPanel panels[] = {
{
	0,
	0,
	0,
	STRIPLED_W,
	STRIPLED_H,
	WRAP_COLUMNS,
	ORIGIN_TOP_LEFT
},
{
	STRIPLED_W*STRIPLED_H, // LED index 256
	STRIPLED_W, // x0=32
	0, // y0=0
	STRIPLED_W,
	STRIPLED_H,
	WRAP_COLUMNS,
	ORIGIN_TOP_LEFT
},
{
  STRIPLED_W*STRIPLED_H*2, // LED index 512
	0, // x0=0
	STRIPLED_H, // y0=8
	STRIPLED_W,
	STRIPLED_H,
	WRAP_COLUMNS,
	ORIGIN_TOP_LEFT
},
{
	STRIPLED_W*STRIPLED_H*3, // LED index 768
	STRIPLED_W, // x0=32
	STRIPLED_H, // y0=8
	STRIPLED_W,
	STRIPLED_H,
	WRAP_COLUMNS,
	ORIGIN_TOP_LEFT
}
};
#define N_PANELS (sizeof(panels) / sizeof(StripLEDPanel))

CRGB leds[STRIPLED_W*STRIPLED_H*N_PANELS];
StripDisplay strip(STRIPLED_GPIO, BITMAP_W, BITMAP_H, leds, panels, N_PANELS);

void setup() {
	FastLED.addLeds<NEOPIXEL,STRIPLED_GPIO>(leds, STRIPLED_W*STRIPLED_H*N_PANELS);
	strip.setup(fontP);
	Serial.begin(9600);
	Serial.println(String(STRIPLED_W*STRIPLED_H*N_PANELS) + String(" leds on gpio ") + String(strip.getGpio()));
}

void loop() {
	// text display API setup
	strip.setFgColor(CRGB(1,1,1));
	strip.setBgColor(CRGB(0,0,0));
	strip.setText("Hey");
	// bitmap level APIs
	strip.setPixel(0,0,CRGB(16,0,0));
	strip.setPixel(BITMAP_W-1,0,CRGB(0,16,0));
	strip.setPixel(0,BITMAP_H-1,CRGB(0,0,16));
	strip.setPixel(BITMAP_W-1,BITMAP_H-1,CRGB(8,0,8));
	// render text on bitmap
	strip.renderText(fontP->getWidth()*2, (BITMAP_H-fontP->getHeight())/2, CRGB(4,2,0));
	// display bitmap
	strip.displayBitmap();
	FastLED.delay(2000);
	// text alignment example
	strip.setFgColor(CRGB(1,1,1));
	// text ALIGN_LEFT, ALIGN_CENTER, ALIGN_RIGHT
	for (int align=ALIGN_LEFT; align<=ALIGN_RIGHT; align++) {
		strip.setAlignment(align);
    int line=1;
    strip.setLine(line);
		strip.displayText();
		FastLED.delay(1000);
	}
	// text scrolling example
	strip.setAlignment(ALIGN_LEFT);
	strip.setFgColor(CRGB(4,2,0));
	strip.setBgColor(CRGB(0,0,1));
	strip.setText("Hello world!");
	for (int offset=0; offset<strip.getTextWidth(); offset++) {
		strip.displayText(offset);
		FastLED.delay(100);
	}
}

**Comment by lyriarte** [comment]
It may be because your device doesn't have enough memory. A few things to try, off the top of my head:

- Run with a serial debugger, check for the "Display bitmap allocation failed" [message](https://github.com/lyriarte/StripDisplay/blob/master/StripDisplay.cpp#L100) at start. 
- Try without displaying text at all, remove the `#define FONT_5x7_FIXED_MEDIUM`, the `fontP` pointer and all text-related code, and use the [setPixel APIs](https://github.com/lyriarte/StripDisplay/blob/master/examples/Stacking/Stacking.ino#L50). If your device is tight on memory, maybe saving the font footprint would let you try your code at lower level.
- Maybe try a device with more memory, like [ESP-12 / NodeMCU](https://en.wikipedia.org/wiki/NodeMCU) with the Arduino IDE.

**Comment by TWICExONCE** [comment]
I'll try with a device with more memory. Thanks!

**Comment by lyriarte** [comment]
Thanks, closing.
